version: '3.8'

services:
  flavorhaven.presentation:
    image: flavorhaven.presentation
    build:
      context: .
      dockerfile: FlavorHaven.Presentation/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      - flavorhaven-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=FlavorHaven
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - flavorhaven-network

volumes:
  postgres-data:

networks:
  flavorhaven-network:
    driver: bridge